language: php
php:
  - 5.4
  - 5.5
  - 5.6

script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --standard=PSR2 ./app ./src
    
notifications:
  email:
    recipients:
    - ricardol@microsoft.com
    on_success: never
    on_failure: always
